// Contact types
export const GET_CONTACTS = 'GET_CONTACTS'
export const CONTACTS_LOADING = 'CONTACTS_LOADING'
export const GET_SELECTED_CONTACT = 'GET_SELECTED_CONTACT'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const SET_CONTACTS = 'SET_CONTACTS'
